    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
    11
    12
    13
    14
    15
    16
    17
    18
    19
    20
    21
    22
    23
    24
    25
    26

  os: Visual Studio 2015


  install:

    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - rustc -vV
    - cargo -vV


  build: false


  test_script:

    - cargo build --verbose
    - cargo test --verbose